//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016_06_13_Workout_Manager_ASP.NET_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechnikmarktEntities : DbContext
    {
        public TechnikmarktEntities()
            : base("name=TechnikmarktEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<exercise> exercises { get; set; }
        public virtual DbSet<stepsdone> stepsdones { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<workout> workouts { get; set; }
        public virtual DbSet<workoutplanentry> workoutplanentries { get; set; }
        public virtual DbSet<workoutstep> workoutsteps { get; set; }
    }
}
