//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016_06_13_Workout_Manager_ASP.NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workoutplanentry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public workoutplanentry()
        {
            this.stepsdones = new HashSet<stepsdone>();
        }
    
        public long wpe_id { get; set; }
        public byte wpe_w_workout { get; set; }
        public System.DateTime wpe_creationdate { get; set; }
        public System.DateTime wpe_scheduledate { get; set; }
        public bool wpe_repeat { get; set; }
        public string wpe_u_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stepsdone> stepsdones { get; set; }
        public virtual user user { get; set; }
        public virtual workout workout { get; set; }
    }
}
